#Here we have defined root logger
log4j.rootLogger=DEBUG,CONSOLE,FILE
 
#Console configuration
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern= %d{dd-MM-yyyy hh:mm:ss}  %c %M -%m%n


#File configuration
log4j.appender.FILE=org.apache.log4j.FileAppender
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.file=./TestResults/AppLogs.log
log4j.appender.FILE.layout.ConversionPattern= %d{dd-MM-yyyy hh:mm:ss}  %c %M -%m%n
log4j.appender.FILE.Append=true 